MULE-7680: fix for HTTP response with multiple HTTP "Set-Cookie" headers in different case that caused exception:
java.lang.IllegalArgumentException: Invalid cookiesObject. Only class org.apache.commons.httpclient.Cookie[] and interface java.util.Map are supported

with response headers like:
SET-COOKIE: header-name-is-uppercase=SET-COOKIE-UPPERCASE-1
Set-Cookie: header-name-is-camelcase=Set-Cookie-CamelCase-1