MULE-14588: Deployment failed due to NoSuchMethodError: Error creatin… (#6633)
...bean with name 'http_request' when running parallel deployments
(cherry picked from commit 28dbd41300a56553de4082a946bc020886cf057c)