MULE-14588: Deployment failed due to NoSuchMethodError: Error creating bean with name 'http_request' when running parallel deployments
The cache added to this factory holds also references to proxies created for Mule (container) componentBuildingDefinitions but this cache is being tied to the application lifecycle, therefore at some point the proxies has unregistered the callbacks but still the Enhancer has enabled the useCache (in order to avoid OOM and creating of classes for the container that are not needed) and the NoSuchMethod is thrown.
As cglib already has the cache managed internally and always returns the same class (when create class is invoked) and only for those cases where classes are created for the application context the cache is set to false) we can just remove this cache that introduced this issues.