NoRetryPolicyTemplate performs (non XA) connection test even switched off.
which probably causes Root Exception stack trace:
com.ibm.db2.jcc.am.XaException: [jcc][t4][10401][12066][4.28.11] XA exception: XAER_OUTSIDE ERRORCODE=-4228, SQLSTATE=null
at com.ibm.db2.jcc.am.b7.c(b7.java:561)
at com.ibm.db2.jcc.am.b7.c(b7.java:590)
at com.ibm.db2.jcc.t4.a3.a(a3.java:1741)
at com.ibm.db2.jcc.t4.a3.a(a3.java:1690)
at com.ibm.db2.jcc.t4.a3.start(a3.java:1593)

when connection is re-used in normal flow.