first attempt:
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   FlowRefTestCase.backpressureFlowRefSub An exception was caught
but it wasn't expected for the test
 Caught exception was:
 org.junit.internal.runners.model.MultipleFailureException: There were 2
errors:
  java.lang.AssertionError(Condition not met)
  java.util.concurrent.ExecutionException(java.net.ConnectException:
Connection refused)
org.junit.internal.runners.model.MultipleFailureException: There were 2
errors:
  java.lang.AssertionError(Condition not met)
  java.util.concurrent.ExecutionException(java.net.ConnectException:
Connection refused)
	at org.junit.runners.model.MultipleFailureException.assertEmpty(MultipleFailureException.java:67)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:39)
	at org.mule.functional.api.exception.ExpectedError$ExpectedErrorStatement.evaluate(ExpectedError.java:197)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

[ERROR]   FlowRefTestCase.flowRefSubFlowErrorNotifications An exception
was caught but it wasn't expected for the test
 Caught exception was:
 org.mule.runtime.core.api.config.ConfigurationException: Couldn't find
configuration property value for key ${port} from properties provider
environment properties provider - within resolver global-properties
configuration attributes trying to process key port - within resolver
environment properties provider trying to process key port - within
resolver global-properties configuration attributes trying to process
key port - within resolver environment properties provider trying to
process key port - within resolver External files trying to process key
port org.mule.runtime.core.api.config.ConfigurationException: Couldn't
find configuration property value for key ${port} from properties
provider environment properties provider - within resolver
global-properties configuration attributes trying to process key port -
within resolver environment properties provider trying to process key
port - within resolver global-properties configuration attributes trying
to process key port - within resolver environment properties provider
trying to process key port - within resolver External files trying to
process key port
Caused by:
org.mule.runtime.config.internal.dsl.model.config.PropertyNotFoundException:
Couldn't find configuration property value for key ${port} from
properties provider environment properties provider - within resolver
global-properties configuration attributes trying to process key port -
within resolver environment properties provider trying to process key
port - within resolver global-properties configuration attributes trying
to process key port - within resolver environment properties provider
trying to process key port - within resolver External files trying to
process key port

[ERROR]   ParallelForEachTestCase.timeout Expected test to throw
exception with cause a value with a class hierarchy containing
org.mule.runtime.core.privileged.routing.CompositeRoutingException
[ERROR]   ScatterGatherRouterTestCase.timeout Expected test to throw
exception with cause a value with a class hierarchy containing
org.mule.runtime.core.privileged.routing.CompositeRoutingException
[ERROR] Errors:
[ERROR]   FlowRefTestCase.recursive:198 » TestTimedOut test timed out
after 60000 millis...
[ERROR]   FlowRefTestCase.recursiveDynamic:203 » TestTimedOut test timed
out after 60000...
[INFO]
[ERROR] Tests run: 53, Failures: 4, Errors: 2, Skipped: 1